# Generated by Django 4.0.5 on 2022-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_departamento_edificio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
